service: firebase-sdk-slow
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  memorySize: 256
  timeout: 10
  logRetentionInDays: 30
  logs:
    httpApi: false

functions:
  index:
    name: firebase-sdk-slow-test
    handler: handler.index
    events:
      - http:
          path: index
          method: get
